### ISSUE TITLE
value error:You are trying to load a weight file containing 80 layers into a model with 4 layers.

### ISSUE THREAD

**Issue by fareesa1** [jutanke/person_reid#7]
```
>>> from reid import reid
Using TensorFlow backend.
2020-03-22 21:38:04.511394: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found
2020-03-22 21:38:04.519173: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
>>> model = reid.ReId()
2020-03-22 21:38:12.905975: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'nvcuda.dll'; dlerror: nvcuda.dll not found
2020-03-22 21:38:12.914315: E tensorflow/stream_executor/cuda/cuda_driver.cc:313] failed call to cuInit: UNKNOWN ERROR (303)
2020-03-22 21:38:12.925451: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: DESKTOP-2UP1E9B
2020-03-22 21:38:12.934758: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: DESKTOP-2UP1E9B
2020-03-22 21:38:12.941920: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2020-03-22 21:38:12.964968: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x22ecf018880 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-03-22 21:38:12.974730: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
fp: /tmp\reid.h5
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Dell-PC\Anaconda3\envs\newenv\lib\site-packages\reid\reid.py", line 62, in __init__
    model.load_weights(filepath)
  File "C:\Users\Dell-PC\Anaconda3\envs\newenv\lib\site-packages\tensorflow\python\keras\engine\training.py", line 249, in load_weights
    return super(Model, self).load_weights(filepath, by_name, skip_mismatch)
  File "C:\Users\Dell-PC\Anaconda3\envs\newenv\lib\site-packages\tensorflow\python\keras\engine\network.py", line 1261, in load_weights
    hdf5_format.load_weights_from_hdf5_group(f, self.layers)
  File "C:\Users\Dell-PC\Anaconda3\envs\newenv\lib\site-packages\tensorflow\python\keras\saving\hdf5_format.py", line 679, in load_weights_from_hdf5_group
    raise ValueError('You are trying to load a weight file '
ValueError: You are trying to load a weight file containing 80 layers into a model with 4 layers.
```

**Comment by jutanke** [comment]
What is your tensorflow version?
